/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_MESSAGING_FILTERED_STATE_MSG_PB_H_INCLUDED
#define PB_MESSAGING_FILTERED_STATE_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _messaging_FILTERED_STATE { 
    double pos_x; 
    double pos_y; 
    double pos_z; 
    double quat_w; 
    double quat_x; 
    double quat_y; 
    double quat_z; 
    double vel_x; 
    double vel_y; 
    double vel_z; 
    double ang_x; 
    double ang_y; 
    double ang_z; 
    double time; 
} messaging_FILTERED_STATE;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define messaging_FILTERED_STATE_init_default    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define messaging_FILTERED_STATE_init_zero       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define messaging_FILTERED_STATE_pos_x_tag       1
#define messaging_FILTERED_STATE_pos_y_tag       2
#define messaging_FILTERED_STATE_pos_z_tag       3
#define messaging_FILTERED_STATE_quat_w_tag      4
#define messaging_FILTERED_STATE_quat_x_tag      5
#define messaging_FILTERED_STATE_quat_y_tag      6
#define messaging_FILTERED_STATE_quat_z_tag      7
#define messaging_FILTERED_STATE_vel_x_tag       8
#define messaging_FILTERED_STATE_vel_y_tag       9
#define messaging_FILTERED_STATE_vel_z_tag       10
#define messaging_FILTERED_STATE_ang_x_tag       11
#define messaging_FILTERED_STATE_ang_y_tag       12
#define messaging_FILTERED_STATE_ang_z_tag       13
#define messaging_FILTERED_STATE_time_tag        14

/* Struct field encoding specification for nanopb */
#define messaging_FILTERED_STATE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   pos_x,             1) \
X(a, STATIC,   SINGULAR, DOUBLE,   pos_y,             2) \
X(a, STATIC,   SINGULAR, DOUBLE,   pos_z,             3) \
X(a, STATIC,   SINGULAR, DOUBLE,   quat_w,            4) \
X(a, STATIC,   SINGULAR, DOUBLE,   quat_x,            5) \
X(a, STATIC,   SINGULAR, DOUBLE,   quat_y,            6) \
X(a, STATIC,   SINGULAR, DOUBLE,   quat_z,            7) \
X(a, STATIC,   SINGULAR, DOUBLE,   vel_x,             8) \
X(a, STATIC,   SINGULAR, DOUBLE,   vel_y,             9) \
X(a, STATIC,   SINGULAR, DOUBLE,   vel_z,            10) \
X(a, STATIC,   SINGULAR, DOUBLE,   ang_x,            11) \
X(a, STATIC,   SINGULAR, DOUBLE,   ang_y,            12) \
X(a, STATIC,   SINGULAR, DOUBLE,   ang_z,            13) \
X(a, STATIC,   SINGULAR, DOUBLE,   time,             14)
#define messaging_FILTERED_STATE_CALLBACK NULL
#define messaging_FILTERED_STATE_DEFAULT NULL

extern const pb_msgdesc_t messaging_FILTERED_STATE_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define messaging_FILTERED_STATE_fields &messaging_FILTERED_STATE_msg

/* Maximum encoded size of messages (where known) */
#define messaging_FILTERED_STATE_size            126

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
