/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_MESSAGING_MOTORS_MSG_PB_H_INCLUDED
#define PB_MESSAGING_MOTORS_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _messaging_MOTORS { 
    int32_t front_left; 
    int32_t front_right; 
    int32_t back_right; 
    int32_t back_left; 
    double time; 
} messaging_MOTORS;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define messaging_MOTORS_init_default            {0, 0, 0, 0, 0}
#define messaging_MOTORS_init_zero               {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define messaging_MOTORS_front_left_tag          1
#define messaging_MOTORS_front_right_tag         2
#define messaging_MOTORS_back_right_tag          3
#define messaging_MOTORS_back_left_tag           4
#define messaging_MOTORS_time_tag                5

/* Struct field encoding specification for nanopb */
#define messaging_MOTORS_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    front_left,        1) \
X(a, STATIC,   SINGULAR, INT32,    front_right,       2) \
X(a, STATIC,   SINGULAR, INT32,    back_right,        3) \
X(a, STATIC,   SINGULAR, INT32,    back_left,         4) \
X(a, STATIC,   SINGULAR, DOUBLE,   time,              5)
#define messaging_MOTORS_CALLBACK NULL
#define messaging_MOTORS_DEFAULT NULL

extern const pb_msgdesc_t messaging_MOTORS_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define messaging_MOTORS_fields &messaging_MOTORS_msg

/* Maximum encoded size of messages (where known) */
#define messaging_MOTORS_size                    53

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
