title = "MocapZMQ"

[vicon]
    server = "192.168.3.249"
    subject = "rex1"

[zmq]
    [zmq.jetson]
        [zmq.jetson.vicon]
            server = "127.0.0.1"
            port = "5002"
        [zmq.jetson.imu]
            server = "127.0.0.1"
            port = "5003"
        [zmq.jetson.filtered_state]
            server = "127.0.0.1"
            port = "5004"
        [zmq.jetson.motors]
            server = "127.0.0.1"
            port = "5005"
        [zmq.jetson.quad_info]
            server = "192.168.3.150"
            port = "5006"

    [zmq.ground]
        [zmq.ground.vicon]
            server = "192.168.3.117" # "127.0.0.1"
            port = "5002"
        [zmq.ground.ground_info]
            server = "192.168.3.117"
            port = "5006"
        [zmq.ground_arduino.vicon]
            server = "127.0.0.1"
            port = "5101"
        [zmq.ground_arduino.imu]
            server = "127.0.0.1"
            port = "5102"


[serial]
    [serial.jetson]
        [serial.jetson.imu_arduino]
            serial_port = "/dev/ttyACM0"
            baud_rate = 57600
        [serial.jetson.motors_arduino]
            serial_port = "/dev/ttyACM1"
            baud_rate = 57600
    [serial.ground]
        [serial.ground.telemetry_radio]
            serial_port = "/dev/tty.usbmodem14201"
            baud_rate = 57600
        [serial.ground.imu_arduino]
            serial_port = "/dev/tty.usbmodem92225501"
            baud_rate = 57600