title = "MocapZMQ"

[vicon]
    server = "192.168.3.194"
    subject = "UnitreeA1"

[zmq]
    [zmq.jetson]
        [zmq.jetson.vicon]
            server = "127.0.0.1"
            port = "5000"
        [zmq.jetson.imu]
            server = "127.0.0.1"
            port = "5002"
        [zmq.jetson.filtered_state]
            server = "127.0.0.1"
            port = "5004"
        [zmq.jetson.motors]
            server = "127.0.0.1"
            port = "5006"
        [zmq.jetson.quad_info]
            server = "127.0.0.1"
            port = "5010"

    [zmq.ground]
        [zmq.ground.vicon]
            server = "127.0.0.2"
            port = "5002"
        # This should be the same thing as [zmq.jetson.link]
        [zmq.ground.quad_info]
            server = "127.0.0.2"
            port = "5010"

[serial]
    [serial.jetson]
        [serial.jetson.imu_arduino]
            serial_port = "/dev/tty.usbmodem14201"
            baud_rate = 57600
    [serial.relay]
        [serial.jetson.relay]
            serial_port = "/dev/tty.usbmodem14201"
            baud_rate = 57600