title = "ZMQ Ports"

[vicon]
    server = "192.168.3.249"
    subject = "coffeetime"

[zmq]
    [zmq.jetson]
        server = "127.0.0.1"
        vicon_port = "5000"
        imu_port = "5002"
        filtered_state_port = "5004"
        # motor_torques = "5006"

    [zmq.vicon_relay]
        server = "127.0.0.1"
        vicon_port = "5000"

[serial]
    [serial.jetson]
        serial_port = "/dev/tty.usbmodem92225501"
        baud_rate = 57600

    [serial.relay]
        serial_port = "/dev/tty.usbmodem92225501"
        baud_rate = 57600