title = "MocapZMQ"

[vicon]
    server = "192.168.3.249"
    subject = "rex1"

[zmq]
    [zmq.jetson]
        [zmq.jetson.vicon]
            server = "127.0.0.1"
            port = "5555"
        [zmq.jetson.imu]
            server = "127.0.0.1"
            port = "5556"

        [zmq.jetson.imu_vicon_relay.in]
            server = "127.0.0.1"
            port = "5557"
        [zmq.jetson.imu_vicon_relay.out]
            server = "127.0.0.1"
            port = "5558"

        [zmq.jetson.motors_relay.in]
            server = "127.0.0.1"
            port = "5559"
        [zmq.jetson.motors_relay.out]
            server = "127.0.0.1"
            port = "5560"


        [zmq.jetson.filtered_state]
            server = "127.0.0.1"
            port = "5561"
        [zmq.jetson.motors]
            server = "127.0.0.1"
            port = "5562"
        [zmq.jetson.quad_info]
            server = "192.168.3.116"
            port = "5563"

    [zmq.ground]
        [zmq.ground.vicon]
            server = "192.168.3.134"
            port = "5555"
        [zmq.ground.ground_info]
            server = "192.168.3.117"
            port = "5556"

[serial]
    [serial.jetson]
        [serial.jetson.imu_arduino]
            serial_port = "/dev/ttyACM1"
            baud_rate = 115200
        [serial.jetson.motors_arduino]
            serial_port = "/dev/ttyACM0"
            baud_rate = 115200
    [serial.macbook]
        [serial.macbook.telemetry_radio]
            serial_port = "/dev/tty.usbserial-D309D5SC"
            baud_rate = 115200
        [serial.macbook.imu_arduino]
            serial_port = "/dev/tty.usbmodem92225501"
            baud_rate = 115200